# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=50, verbose_name='事件名')),
                ('event_cate', models.CharField(default='告急信息', max_length=50, verbose_name='事件类型')),
                ('event_src', models.CharField(default='0.0.0.0', max_length=50, verbose_name='事件由来IP')),
            ],
            options={
                'verbose_name': '事件',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now=True, verbose_name='时间发生时间')),
                ('extra', models.CharField(blank=True, max_length=150, verbose_name='状态备注')),
                ('connect_person', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='状态参与人员')),
            ],
            options={
                'verbose_name': '事件状态',
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(blank=True, max_length=50, verbose_name='状态')),
                ('iStation', models.IntegerField(verbose_name='状态INT')),
            ],
            options={
                'verbose_name': '状态集合',
            },
        ),
        migrations.AddField(
            model_name='stat',
            name='stat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.Stations', verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Stat', verbose_name='事件的当前状态'),
        ),
    ]
