# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20171109_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(default='告急信息', max_length=50, verbose_name='事件类型')),
            ],
            options={
                'verbose_name': '事件类型集合',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='看过'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventCate', verbose_name='事件类型'),
        ),
    ]
