# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20171109_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBase',
            fields=[
                ('event_name', models.CharField(blank=True, max_length=50, verbose_name='事件名')),
                ('event_src', models.CharField(default='0.0.0.0', max_length=20, verbose_name='泄露源')),
                ('to_server', models.CharField(default='0.0.0.0', max_length=20, verbose_name='流向IP')),
                ('port', models.CharField(default='443', max_length=20, verbose_name='端口')),
                ('happened_date', models.DateField(auto_now=True, verbose_name='发生日期')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventCate', verbose_name='数据类型')),
            ],
            options={
                'verbose_name': '事件',
            },
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('is_seen', models.BooleanField(default=False, verbose_name='看过')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='事件的处理ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventBase', verbose_name='事件')),
                ('event_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Stat', verbose_name='事件的当前状态')),
            ],
            options={
                'verbose_name': '事件详细',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_cate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_stat',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
