# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 01:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0006_auto_20171110_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='connect_person',
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='connect_person',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='状态参与人员'),
        ),
    ]
