# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20171110_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
