# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20171110_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
