# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20171110_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='stations',
            name='iStation',
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='extra_add',
            field=models.TextField(default='', verbose_name='添加备注'),
        ),
        migrations.AddField(
            model_name='stat',
            name='desc',
            field=models.CharField(blank=True, max_length=150, verbose_name='状态描述'),
        ),
    ]
